### ISSUE TITLE
How to avoid margins?

### ISSUE THREAD

**Issue by Klaus-Tockloth** [de-souza/hugo-flex#6]
It seems that 'Hugo Flex' is excellent for my purposes.

If I view the demo on a smartphone I get this (1920x1080):

![Screenshot_20190414-112717_Chrome](https://user-images.githubusercontent.com/5493128/56091108-c5f30480-5eaa-11e9-9d2f-011bf8aed243.jpg)

... and on a tablet (or desktop) that (2560x1600):

![Screenshot_2019-04-14-11-27-44](https://user-images.githubusercontent.com/5493128/56091112-d1dec680-5eaa-11e9-88b0-97ff7f7c2e80.png)

Question: How is it possible to avoid the empty margins on a tablet or desktop?

Or in other words: How can the full width of the screen be used for content?

**Comment by de-souza** [comment]
Hi, thank you very much for your suggestion.

It is now possible to specify the maximum width with a parameter in your site configuration. In your case, this parameter can be set to an empty value:

```yaml

params:
  color: teal  # Any color in CSS syntax
  width:
  footer: Except where otherwise noted, content on this site is licensed under
    a <a href="http://creativecommons.org/licenses/by/4.0/" rel="license">
    Creative Commons Attribution 4.0 International License</a>.
  rss: To subscribe to this RSS feed, copy its address and paste it into your
    favorite feed reader.
```
